spring: 
    profiles:        active: 
        - dog
        - EN
        - prod
guru:
    username: ymlDefaultUserName
    password: ymlDefaultPassword    jdbcurl: ymlDefaultJDBCUrl
    
---
spring:    profiles: prod
guru: 
    username: YmlProdUserName
    password: ymlProdPassword
    jdbcurl: YmlProdJdbcUrl

  
